[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "20.19.0"

[[redirects]]
from = "/api/*"
to = "http://109.73.206.144:6969/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200